apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillerwhale-deployment-svc-json
  labels:
    app: skillerwhale-svc-json
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skillerwhale-svc-json
  template:
    metadata:
      labels:
        app: skillerwhale-svc-json
    spec:
      containers:
      - name: skillerwhale-svc-json
        image: skillerwhale/svc-json:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: skillerwhale-svc-json
spec:
  selector:
    app: skillerwhale-svc-json
  ports:
  - protocol: HTTP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillerwhale-deployment-svc-html
  labels:
    app: skillerwhale-svc-html
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skillerwhale-svc-html
  template:
    metadata:
      labels:
        app: skillerwhale-svc-html
    spec:
      containers:
        - name: skillerwhale-svc-html
          image: skillerwhale/svc-html:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # NOTE: the DNS name is resolved by k8s DNS service
            - name: REMOTE_URL
              value: "http://skillerwhale-svc-json"
---
apiVersion: v1
kind: Service
metadata:
  name: skillerwhale-svc-html
spec:
  selector:
    app: skillerwhale-svc-html
  ports:
  - protocol: HTTP
    port: 8080
    targetPort: 8080
