apiVersion: v1
kind: Pod
metadata:
  name: skillerwhale-svc-json
spec:
  containers:
    - name: skillerwhale-svc-json
      image: skillerwhale/svc-json:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: CACHE_PATH
          value: "/caches-warmed"
    - name: skillerwhale-cache-warmer
      image: busybox:1.28
      imagePullPolicy: Always
      command: ['sh', '-c', 'sleep 10; touch /caches-warmed; while true; do sleep 30; done;']
