apiVersion: v1
kind: Pod
metadata:
  name: svc-json
  labels:
    app: svc-json
spec:
  containers:
    - name: svc-json
      image: skillerwhale/svc-json:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: ID
          value: "pod-behind-a-service"
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-html
  labels:
    app: svc-html
spec:
  containers:
    - name: svc-html
      image: skillerwhale/svc-html:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        # NOTE: the DNS name is resolved by k8s DNS service
        - name: REMOTE_URL
          value: "http://svc-json"
