apiVersion: v1
kind: Pod
metadata:
  name: skillerwhale-svc-json
  labels:
    app: svc-json
spec:
  containers:
    - name: skillerwhale-svc-json
      image: skillerwhale/svc-json:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: ID
          value: "foo-bar-id"
---
apiVersion: v1
kind: Service
metadata:
  name: skillerwhale-svc-json
spec:
  selector:
    app: svc-json
  ports:
  - protocol: HTTP
    port: 80
    targetPort: 80
  type: LoadBalancer
