apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillerwhale-deployment
  labels:
    app: skillerwhale-svc-json
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skillerwhale-svc-json
  template:
    metadata:
      labels:
        app: skillerwhale-svc-json
    spec:
      containers:
      - name: skillerwhale-svc-json
        image: skillerwhale/svc-json:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: ID
            value: "backend-json-service"
